### PR TITLE
Do not start QueueProcesserThread on config update.

### PR DESCRIPTION
**Pull request by jugmac00**
... as this is unexpected.

I'd be very happy to also cover the `if REQUEST` idiom, if somebody could point me to
- how to make a simple REQUEST object for testing (which I probably could figure out myself)
- and especially how to satisfy the security restrictions, see below

With a super simple dummy request object(`request = {}`) I get this test error, which I do not know how to handle.
```
AccessControl.unauthorized.Unauthorized: You are not allowed to access 'manage_page_header' in this context
```

This is the first pull request (for #14) - once accepted, I will make another one for the 2.13 branch, as I need a backport for my Zope app, which currently still runs on 2.13.

### CODE REVIEW

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2019-5-28 06:59 -0700:
>... as this is unexpected.
>
>I'd be very happy to also cover the `if REQUEST` idiom, if somebody could point me to
>- how to make a simple REQUEST object for testing (which I probably could figure out myself)

I typically use `Testing.ZopeTestCase.ZopeTestCase` as base
class for my Zope tests. It sets up a minimal Zope environment.
Especially, the test instance has a `self.app` (Zope's application root).
From this, you can get a test request with `self.app.REQUEST`.

If you have got Zope's application object ("app") in any way
(e.g. from a `zconsole`) you can wrap it into a test request
with `Testing.makerequest.makerequest`).

**Comment by dataflake** [comment]
I wish you would not mix a completely unrelated cleanup of the email addresses used in the tests into this PR. Now you have a huge diff you're asking people to look at where very little actually concerns the issue in question. Please do not do that in the future. It makes reviewing unneccessarily hard. Thank you.

**Comment by dataflake** [comment]
It is somewhat pointless to test the ZMI redirect at the end. That code has not changed except for moving a single line around. Furthermore, the redirect is completely unrelated to the actual issue you're fixing here. I'm going to merge this as-in.

**Comment by icemac** [comment]
An additional entry in the change log would be nice.

**Comment by jugmac00** [comment]
@d-maurer Thanks a lot for pointing me to `Testing.ZopeTestCase.ZopeTestCase` which I did not know until now!

@dataflake Thanks for merging!

When I work on code, I usually look for what Martin Fowler calls **opportunistic refactoring** or Robert Martin calls **the boyscout rule** = "always leave the code behind in a better state than you found it".

I am well aware that reviews and therefore commits should be easy scannable.

By the way... Did you notice that I put the domain name change into a separate commit?
https://github.com/zopefoundation/Products.MailHost/pull/18/commits/c17e511fb776e354b80382df8f3029f3e8e547bc
Although there are many changes, Github offers even inline highlighting, so the review of the domain name change should not take more than one minute.

Anyway, if you prefer smaller pull requests, I will do so.

**Comment by jugmac00** [comment]
@icemac Thanks for the hint! Please see #19

**Comment by dataflake** [comment]
I do not look at separate commit. I look at the final change set.

You're welcome to use whatever technique you want, but if you end up with a large change set you're making life hard for the reviewer. We're all volunteers here who spend their spare time.

You can always create separate PRs for unrelated changes.

**Pull request merged**
